spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qyj-store?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: xxxxx
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.qyj.store.entity
  mapperLocations: classpath*:com/qyj/store/dao/mapper/*.xml

server:
  port: 8080

#打印sql日志
logging:
  level:
    com:
      qyj:
        store:
          dao: debug
  path: /usr/local/qyj/logs
