spring:
  datasource:
    url: jdbc:mysql://www.stone.com:3306/qyj-store
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.qyj.store.entity
  mapperLocations: classpath*:com/qyj/store/dao/mapper/*.xml

server:
  port: 8080
  servlet:
    session:
      timeout: 10s

#打印sql日志
logging:
  level:
    com:
      qyj:
        store:
          dao: debug
  path: D:\workspace_idea\logs
