spring:
  datasource:
    url: jdbc:mysql://stl.server.com:3306/qyj_store?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.qyj.store.entity
  mapperLocations: classpath*:com/qyj/store/dao/mapper/*.xml

server:
  port: 8080

#打印sql日志
logging:
  level:
    com:
      qyj:
        store:
          dao: debug
  path: F:\workspaces\idea_workspace\logs
