INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('业务管理', 'MENU', 'homeBusManage', 1, '1', NULL, 'enable', NULL, '2018-11-28 10:09:48', 1, '2018-11-28 10:09:48', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('数据统计', 'MENU', 'homeDataStatistics', 2, '2', NULL, 'enable', NULL, '2018-11-28 10:10:29', 1, '2018-11-28 10:10:29', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('系统管理', 'MENU', 'homeAdminManage', 3, '3', NULL, 'enable', NULL, '2018-11-28 10:10:47', 1, '2018-11-28 10:10:47', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('产品管理', 'MENU', 'homeProductList', 11, 'admin/product/listProductPage', NULL, 'enable', NULL, '2018-11-28 10:11:15', 1, '2018-11-28 10:11:15', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('库存数据', 'MENU', 'homeStoreInfo', 12, 'admin/product/listProductPage', NULL, 'enable', NULL, '2018-11-28 10:11:33', 1, '2018-11-28 10:11:33', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('进货单', 'MENU', 'homeStockOrder', 13, 'admin/stockOrder/listStockOrderPage', NULL, 'enable', NULL, '2018-11-28 10:11:46', 1, '2018-11-28 10:11:46', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('销售单', 'MENU', 'homeSellOrder', 14, 'admin/sellOrder/listSellOrderPage', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('菜单管理', 'MENU', 'homeMenu', 31, 'admin/menu/queryMenuTree', NULL, 'enable', NULL, '2018-12-03 17:50:55', 1, '2018-12-03 17:50:57', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('角色管理', 'MENU', 'homeRole', 32, 'admin/role/loadRolePage', NULL, 'enable', NULL, '2018-12-03 17:53:46', 1, '2018-12-03 17:53:50', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('用户管理', 'MENU', 'homeUser', 33, 'admin/user/loadUserInfoList', NULL, 'enable', NULL, '2018-12-03 17:54:23', 1, '2018-12-03 17:54:28', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('加载菜单', 'FUN', 'homeMenuInfo', 311, 'admin/menu/getMenuById', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('添加菜单', 'FUN', 'homeAddMenu', 312, 'admin/menu/addMenu', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('更新菜单', 'FUN', 'homeUpdateMenu', 313, 'admin/menu/updateMenu', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('删除菜单', 'FUN', 'homeDeleteMenu', 314, 'admin/menu/deleteMenu', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('加载角色', 'FUN', 'homeRoleInfo', 321, 'admin/role/getRoleById', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('添加角色', 'FUN', 'homeAddRole', 322, 'admin/role/addRole', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('更新角色', 'FUN', 'homeUpdateRole', 323, 'admin/role/editRole', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('删除角色', 'FUN', 'homeDeleteRole', 324, 'admin/role/delRole', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('加载用户', 'FUN', 'homeUserInfo', 331, 'admin/user/getUserRoleData', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('添加用户', 'FUN', 'homeAddUser', 332, 'admin/user/addUser', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('更新用户', 'FUN', 'homeUpdateUser', 333, 'admin/user/updateUser', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('删除用户', 'FUN', 'homeDeleteUser', 334, 'admin/user/delUser', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('启禁用户', 'FUN', 'homeUpdateUserEnable', 335, 'admin/user/updateUserEnable', NULL, 'enable', NULL, '2018-11-28 10:12:01', 1, '2018-11-28 10:12:01', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('获取产品信息', 'FUN', 'homeProductInfo', 111, 'admin/product/getProductInfo', NULL, 'enable', NULL, '2018-12-04 18:02:02', 1, '2018-12-04 18:09:08', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('保存产品', 'FUN', 'homeSaveProduct', 112, 'admin/product/saveProductInfo', NULL, 'enable', NULL, '2018-12-05 09:28:00', 1, '2018-12-05 09:42:05', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('删除产品', 'FUN', 'homeDelProduct', 113, 'admin/product/delProductInfo', NULL, 'enable', NULL, '2018-12-05 09:28:59', 1, '2018-12-05 09:28:59', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('添加进货单', 'FUN', 'homeAddStockOrder', 131, 'admin/stockOrder/addStockOrder', NULL, 'enable', NULL, '2018-12-05 09:32:29', 1, '2018-12-05 09:32:29', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('获取进货单', 'FUN', 'homeGetStockOrder', 132, 'admin/stockOrder/getStockOrderInfo', NULL, 'enable', NULL, '2018-12-05 09:33:40', 1, '2018-12-05 09:33:40', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('更新进货单', 'FUN', 'homeUpdateStockOrder', 133, 'admin/stockOrder/updateStockOrder', NULL, 'enable', NULL, '2018-12-05 09:34:30', 1, '2018-12-05 09:34:30', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('删除进货单', 'FUN', 'homeDeleteStockOrder', 134, 'admin/stockOrder/deleteStockOrder', NULL, 'enable', NULL, '2018-12-05 09:34:55', 1, '2018-12-05 09:34:55', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('添加销售单', 'FUN', 'homeAddSellOrder', 141, 'admin/sellOrder/addSellOrder', NULL, 'enable', NULL, '2018-12-05 09:36:24', 1, '2018-12-05 09:36:24', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('获取销售单', 'FUN', 'homeGetSellOrder', 142, 'admin/sellOrder/getSellOrderInfo', NULL, 'enable', NULL, '2018-12-05 09:36:56', 1, '2018-12-05 09:36:56', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('更新销售单', 'FUN', 'homeUpdateSellOrder', 143, 'admin/sellOrder/updateSellOrder', NULL, 'enable', NULL, '2018-12-05 09:37:23', 1, '2018-12-05 09:37:23', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('删除销售单', 'FUN', 'homeDeleteSellOrder', 144, 'admin/sellOrder/deleteSellOrder', NULL, 'enable', NULL, '2018-12-05 09:37:50', 1, '2018-12-05 09:37:50', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('买家信息', 'MENU', 'homeSeller', '15', 'admin/buyer/listUserPage;admin/buyer/getUserInfo', NULL, 'enable', '', '2019-02-21 17:10:33', '1', '2019-02-21 17:13:48', '1');
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('增加买家', 'FUN', 'homeAddSeller', '151', 'admin/buyer/insertUserInfo', NULL, 'enable', 'null', '2019-02-21 17:15:26', '1', '2019-02-21 17:15:26', '1');
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('更新买家', 'FUN', 'homeUpdateSeller', '152', 'admin/buyer/updateUserInfo', NULL, 'enable', 'null', '2019-02-21 17:16:26', '1', '2019-02-21 17:16:26', '1');
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('买家账单金额统计', 'MENU', 'homeUserBillStatistics', 21, 'admin/sellOrder/listUserOrderSumPage', NULL, 'enable', NULL, '2018-11-28 10:10:29', 1, '2018-11-28 10:10:29', 1);
INSERT INTO `qyj_store`.`sys_menu`(`name`, `menuType`, `menuCode`, `sortNumber`, `url`, `moreUrl`, `status`, `remark`, `createTime`, `createUser`, `updateTime`, `updateUser`) VALUES ('销售产品按月统计', 'MENU', 'homeUserBillStatistics', 21, 'admin/statistics/listSellProductMonthPage', NULL, 'enable', NULL, '2018-11-28 10:10:29', 1, '2018-11-28 10:10:29', 1);




update sys_menu set parentId = 0 where sortNumber < 10 and parentId is null;
update sys_menu m1, sys_menu m2
set m2.parentId = m1.id
where m1.sortNumber * 10 < m2.sortNumber and m1.sortNumber * 10 + 10 > m2.sortNumber and m2.parentId is null;
